apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-db-config
  labels:
    app: psql-db
data:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
  POSTGRES_DB: testdb


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-db-pv
  labels:
    type: local
    app: psql-db
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-db-pv-claim
  labels:
    app: psql-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-db
spec:
  selector:
    matchLabels:
      app: psql-db
  template:
    metadata:
      labels:
        app: psql-db
    spec:
      containers:
      - name: psql-db
        image: postgres:12
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: psql-db-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: psql-db
        ports:
        - containerPort: 5432
      volumes:
        - name: psql-db
          persistentVolumeClaim:
            claimName: psql-db-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: psql-db
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: psql-db
