apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-users
spec:
  selector:
    matchLabels:
      app: go-users
  template:
    metadata:
      labels:
        app: go-users
    spec:
      containers:
      - name: go-users
        image: kilgorevonnegut/go-user-microservice:v5
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ORDER_SERVICE
          value: "order"
        - name: PORT
          value: "8080"
        - name: APP_NAME
          value: "go-users-microservice"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: go-users-svc
spec:
  selector:
    app: go-users
  ports:
  - port: 8080
    targetPort: 8080

