apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-users
spec:
  selector:
    matchLabels:
      app: go-users
  template:
    metadata:
      labels:
        app: go-users
    spec:
      containers:
      - name: go-users
        image: kilgorevonnegut/go-user-microservice:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: go-users-svc
spec:
  selector:
    app: go-users
  ports:
  - port: 8081
    targetPort: 8081

