apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-users
spec:
  selector:
    matchLabels:
      app: go-users
  template:
    metadata:
      labels:
        app: go-users
    spec:
      containers:
      - name: go-users
        image: kilgorevonnegut/go-user-microservice:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: PORT
          value: "8080"
        - name: APP_NAME
          value: "go-users-microservice"
        - name: TICKET_SERVICE
          value: "go-ticket" #k8s will find the service with this name and use its IP address
        - name: FRONT_END_ENDPOINT
          value: "http://localhost:3000"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: go-users
spec:
  type: ClusterIP
  selector:
    app: go-users
  ports:
  - port: 80
    targetPort: 8080

