all: build_and_publish

build_and_publish: \
	build \
	publish

build:
	@echo "------------------------------"
	@echo "Building go user microservice"
	@echo "------------------------------"
	docker build . -t kilgorevonnegut/go-user-microservice:v1

publish:
	@echo "WIP :)"
