apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ticket
spec:
  selector:
    matchLabels:
      app: go-ticket
  template:
    metadata:
      labels:
        app: go-ticket
    spec:
      containers:
      - name: go-ticket
        image: kilgorevonnegut/go-ticket-microservice:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: PORT
          value: "8081"
        - name: APP_NAME
          value: "go-ticket-microservice"
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: go-ticket-svc
spec:
  selector:
    app: go-ticket
  ports:
  - port: 8081
    targetPort: 8081
