all: build_and_publish

build_and_publish:\
	build \
	publish

build:
	@echo "------------------------------"
	@echo "Building go ticket microservice"
	@echo "------------------------------"
	docker build . -t kilgorevonnegut/go-ticket-microservice:v1

publish:
	@echo "WIP :)"
